[package]
name = "tapi.rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.74"
axum = "0.6.20"
frunk = "0.4.2"
hlist = "0.1.2"
hyper = "0.14.27"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full"] }
